### ISSUE TITLE
Can't install django-statsd 1.9.0

### ISSUE THREAD

**Issue by priteau** [WoLpH/django-statsd#6]
The new 1.9.0 release of django-statsd cannot be installed if python-statsd is not already present:

```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import django_statsd
  File "/Users/priteau/django-statsd-1.9.0/django_statsd/__init__.py", line 1, in <module>
    from django_statsd.middleware import (
  File "/Users/priteau/django-statsd-1.9.0/django_statsd/middleware.py", line 8, in <module>
    import statsd
ImportError: No module named statsd
```

This is caused by this import: https://github.com/WoLpH/django-statsd/blob/v1.9.0/setup.py#L7

**Comment by mukeshrock7897** [comment]
For This problem solution is
Enter in Your Virtual Enviroment write command
workon VirtualEnvironmentName
